name: Working with scverse objects in backed mode
description: |
    In this tutorial we show how to work with scverse data objects without loading the full 
    datasets in memory. AnnData and MuData objects are saved to disk as .h5ad and .h5mu files. 
    These formats save HDF5 stores (via h5py) that can be accessed without loading heavy data 
    matrices in memory (i.e. in backed mode), as a “read-only” object.
link: https://scverse-tutorials.readthedocs.io/en/latest/notebooks/scverse_data_backed.html#working-with-scverse-objects-in-backed-mode
image: icon.svg
primary_category: Data structures
tags:
    - data format
packages:
    - anndata
    - mudata
    - scanpy
authors:
